Urigo/accounter-fullstack

packages/server/src/modules/financial-entities/helpers/business-transactions.helper.ts
packages/server/src/modules/financial-entities/resolvers/business-transactions.resolver.ts
packages/server/src/modules/ledger/helpers/fee-transactions.ts
packages/server/src/modules/ledger/helpers/ledgrer-storage.helper.ts
packages/server/src/modules/ledger/helpers/salary-charge-ledger.helper.ts
packages/server/src/modules/ledger/helpers/utils.helper.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/business-trip-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/common-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/conversion-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/dividend-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/internal-transfer-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/monthly-vat-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/salary-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger.resolver.ts
packages/server/src/modules/reports/helpers/vat-report.helper.ts
packages/server/src/shared/constants.ts
packages/server/src/shared/types/index.ts
packages/server/src/shared/types/ledger.ts

Enhance exchange rates expenses records

---

packages/migrations/src/actions/2024-02-22T21-37-11.charge-year-of-relevance.ts
packages/migrations/src/run-pg-migrations.ts

Cross year charges ledger

---

packages/migrations/src/actions/2024-02-26T11-01-45.centralize-financial-entities-shared-columns.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules/financial-entities/providers/businesses.provider.ts
packages/server/src/modules/financial-entities/providers/financial-entities.provider.ts
packages/server/src/modules/financial-entities/providers/tax-categories.provider.ts
packages/server/src/modules/financial-entities/resolvers/businesses.resolver.ts
packages/server/src/modules/financial-entities/resolvers/financial-entities.resolver.ts
packages/server/src/modules/financial-entities/typeDefs/businesses.graphql.ts
packages/server/src/modules/financial-entities/typeDefs/tax-categories.graphql.ts

Remove `name` and `sort_code` columns from business & tax categories DB tables

Centralize financial entities shared columns

---

packages/client/src/components/common/forms/edit-charge.tsx
packages/client/src/components/common/modals/edit-charge-modal.tsx
packages/migrations/src/actions/2024-03-18T17-29-15.convert-charges-year-to-years-of-relevance.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules/charges/providers/charges.provider.ts
packages/server/src/modules/charges/resolvers/charges.resolver.ts
packages/server/src/modules/charges/resolvers/common.ts
packages/server/src/modules/charges/typeDefs/charges.graphql.ts
packages/server/src/modules/ledger/helpers/cross-year-ledger.helper.ts

closes #501 
waiting for [accountant approval](https://guild-oss.slack.com/archives/C06AKLMKQ14/p1710779627047909?thread_ts=1710769415.745589&cid=C06AKLMKQ14)

Logic for split-year charge

---

packages/migrations/src/actions/2024-03-21T11-54-00.exempt-dealers-business-flag.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules/charges/helpers/validate.helper.ts
packages/server/src/modules/financial-entities/providers/businesses.provider.ts

Support exempt dealers VAT validation

---

.changeset/stale-windows-decide.md
packages/migrations/src/actions/2024-04-01T17-36-20.extend-charges-business-array-with-ledger.ts
packages/migrations/src/run-pg-migrations.ts

Fix tax categories missing from business transactions view

---

packages/client/src/components/reports/trial-balance-report/trial-balance-report-account.tsx
packages/client/src/components/reports/trial-balance-report/trial-balance-report-group.tsx
packages/client/src/components/reports/trial-balance-report/trial-balance-report-sort-code.tsx
packages/client/src/components/reports/trial-balance-report/trial-balance-table.tsx

Trial balance UI enhancement: Clearer amounts

---

packages/client/src/components/businesses/businesses-filters.tsx
packages/client/src/components/businesses/index.tsx
packages/server/src/modules/financial-entities/helpers/utils.helper.ts
packages/server/src/modules/financial-entities/resolvers/businesses.resolver.ts
packages/server/src/modules/financial-entities/typeDefs/businesses.graphql.ts

Add name filter to business screen

---

packages/client/src/components/all-charges/all-charges-row.tsx
packages/client/src/components/all-charges/cells/counterparty.tsx
packages/client/src/components/all-charges/charge-extended-info.tsx
packages/client/src/components/common/buttons/regenerate-ledger-records-button.tsx
packages/client/src/components/common/buttons/toggle-expansion-button.tsx
packages/client/src/components/common/buttons/toggle-merge-selected.tsx

Charge UI enhancements

---

packages/client/src/components/common/forms/business-card.tsx
packages/server/src/modules/financial-entities/resolvers/businesses.resolver.ts
packages/server/src/modules/financial-entities/typeDefs/businesses.graphql.ts

UI: enable editing business exempt dealer flag

---

packages/client/src/components/all-charges/ledger-records/cells/account-details.tsx
packages/client/src/components/all-charges/ledger-records/cells/general-date.tsx
packages/client/src/components/all-charges/ledger-records/ledger-record-row.tsx
packages/client/src/components/all-charges/ledger-records/ledger-record-table.tsx

Enhance ledger records changes UI

---

packages/server/src/modules/ledger/helpers/utils.helper.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/common-ledger-generation.resolver.ts

Enhance handling multiple foreign currencies charges' ledger

---

packages/server/src/modules/ledger/resolvers/ledger-generation/salary-ledger-generation.resolver.ts

Balance foreign currencies on salary charges

---

packages/server/src/modules/ledger/resolvers/ledger-generation/common-ledger-generation.resolver.ts
packages/server/src/shared/constants.ts

Use default tax category in case it's missing

---

packages/server/src/modules/ledger/helpers/ledgrer-storage.helper.ts
packages/server/src/modules/ledger/helpers/salary-charge-ledger.helper.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/salary-ledger-generation.resolver.ts

Use last day of month as date for salary ledger records

---

.changeset/@accounter_client-686-dependencies.md
.eslintrc.cjs
packages/client/src/app.tsx
packages/client/src/components/charges-ledger-validation.tsx
packages/client/src/components/common/menu.tsx
packages/client/src/components/common/nav-bar.tsx
packages/server/src/modules/common/typeDefs/common.graphql.ts
packages/server/src/modules/ledger/resolvers/ledger.resolver.ts
packages/server/src/modules/ledger/typeDefs/ledger.graphql.ts

Feature: ledger changes list logic & UI

---

codegen.ts
packages/kraken-scrapper/src/index.ts
packages/kraken-scrapper/src/store.ts
packages/migrations/src/actions/2024-05-21T19-06-42.refactor-financial-accounts.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules/documents/resolvers/document-handling.ts
packages/server/src/modules/financial-accounts/providers/financial-accounts.provider.ts
packages/server/src/modules/financial-accounts/resolvers/common.ts
packages/server/src/modules/financial-entities/providers/tax-categories.provider.ts
packages/server/src/modules/ledger/helpers/common-charge-ledger.helper.ts
packages/server/src/modules/ledger/helpers/fee-transactions.ts
packages/server/src/modules/ledger/helpers/utils.helper.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/bank-deposit-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/conversion-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/internal-transfer-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/monthly-vat-ledger-generation.resolver.ts

Refactor financial accounts table

---

packages/server/src/modules/ledger/resolvers/ledger-generation/dividend-ledger-generation.resolver.ts

Enhance dividends exchange rates logic

---

packages/client/src/components/all-charges/ledger-records/cells/account-details.tsx
packages/server/src/modules/ledger/resolvers/ledger-generation/dividend-ledger-generation.resolver.ts

Refactor ledger generation for dividends

---

packages/server/src/modules/ledger/resolvers/ledger-generation/monthly-vat-ledger-generation.resolver.ts

VAT charges balance fix

---

packages/server/src/modules/ledger/resolvers/ledger-generation/salary-ledger-generation.resolver.ts

Fix: salary month further adjustments

---

packages/server/src/modules/ledger/resolvers/ledger-generation/bank-deposit-ledger-generation.resolver.ts

Enhancement: Better bank deposit error indications

---

packages/server/src/modules/ledger/resolvers/ledger.resolver.ts

Fix: on regenerate ledger, run over updated records (keep only ID)

---

packages/client/src/components/all-charges/charge-errors.tsx
packages/server/src/modules/charges/resolvers/charges.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/bank-deposit-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/business-trip-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/common-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/conversion-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/dividend-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/internal-transfer-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/monthly-vat-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/salary-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger.resolver.ts
packages/server/src/modules/ledger/typeDefs/ledger.graphql.ts

Fix: multiple ledger records generation

---

packages/server/src/modules/ledger/helpers/cross-year-ledger.helper.ts
packages/server/src/shared/constants.ts

Fix: multiple-year charge ledger

---

.changeset/@accounter_green-invoice-graphql-664-dependencies.md
.changeset/@accounter_hashavshevet-mesh-664-dependencies.md
.changeset/@accounter_payper-mesh-664-dependencies.md
codegen.ts
package.json
packages/green-invoice-graphql/json-schemas/greenInvoice.json
packages/green-invoice-graphql/package.json
packages/green-invoice-graphql/src/.meshrc.yaml
packages/green-invoice-graphql/src/index.ts
packages/hashavshevet-mesh/package.json
packages/payper-mesh/package.json
packages/server/src/modules/app-providers/green-invoice.ts
packages/server/src/modules/documents/helpers/green-invoice.helper.ts
packages/server/src/modules/documents/resolvers/document-handling.ts
packages/server/src/modules/documents/resolvers/documents.resolver.ts
yarn.lock

Green Invoice new API adjustments

---

packages/server/src/modules/ledger/resolvers/ledger-generation/monthly-vat-ledger-generation.resolver.ts
packages/server/src/modules/salaries/helpers/get-month.helper.ts
packages/server/src/shared/helpers/misc.ts

Fix monthly VAT charges to handle double-month payments

---

packages/server/src/modules/app-providers/green-invoice.ts

On OCR fail, return empty draft

---

packages/server/src/modules/documents/helpers/validate-document-vat.helper.ts
packages/server/src/modules/ledger/helpers/common-charge-ledger.helper.ts
packages/server/src/modules/reports/helpers/vat-report.helper.ts

On wrong VAT amount - log instead of throw error

---

packages/client/src/components/reports/vat-monthly-report/expenses-section/expenses-row.tsx
packages/client/src/components/reports/vat-monthly-report/income-section/income-row.tsx
packages/server/src/modules/ledger/helpers/monthly-vat-ledger-generation.helper.ts
packages/server/src/modules/reports/helpers/pcn.helper.ts
packages/server/src/modules/reports/helpers/vat-report.helper.ts
packages/server/src/modules/reports/resolvers/reports.resolver.ts
packages/server/src/modules/reports/typeDefs/vat-report.graphql.ts

Better local-foreign naming for VAT report + income records UI fix

---

packages/server/src/modules/ledger/helpers/misc-expenses-ledger.helper.ts

Use misc expenses date as default (over transaction's event date)

---

.eslintrc.cjs
packages/client/src/app.tsx
packages/client/src/components/layout/sidebar.tsx
packages/client/src/components/reports/tax-report/index.tsx
packages/client/src/components/reports/tax-report/tax-report-filters.tsx
packages/server/src/modules/reports/helpers/profit-and-loss.helper.ts
packages/server/src/modules/reports/index.ts
packages/server/src/modules/reports/resolvers/reports.resolver.ts
packages/server/src/modules/reports/resolvers/reports/tax-report.ts
packages/server/src/modules/reports/typeDefs/tax-report.graphql.ts

Tax report

---

.changeset/@accounter_client-928-dependencies.md
.changeset/@accounter_client-932-dependencies.md
.changeset/@accounter_modern-poalim-scraper-928-dependencies.md
.changeset/@accounter_modern-poalim-scraper-932-dependencies.md
package.json
packages/client/package.json
packages/etana-scrapper/package.json
packages/etherscan-scrapper/package.json
packages/hashavshevet-mesh/package.json
packages/kraken-scrapper/package.json
packages/modern-poalim-scraper/package.json
yarn.lock

Reverts Urigo/accounter-fullstack#928

Revert "fix(deps): update all patch dependencies"

---

packages/server/src/modules/reports/helpers/tax.helper.ts
packages/server/src/modules/reports/resolvers/reports/profit-and-loss-report.resolver.ts
packages/server/src/modules/reports/resolvers/reports/tax-report.ts

Profit and loss report: add tax calculation

---

.eslintrc.cjs
packages/client/src/components/common/forms/edit-charge.tsx
packages/client/src/components/common/inputs/charge-spread-input.tsx
packages/client/src/components/common/inputs/index.ts
packages/client/src/components/common/inputs/tags-input.tsx
packages/client/src/components/common/modals/edit-charge-modal.tsx
packages/migrations/src/actions/2024-07-18T13-43-02.enhance-charge-spreading.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules/charges/index.ts
packages/server/src/modules/charges/providers/charge-spread.provider.ts
packages/server/src/modules/charges/resolvers/charges.resolver.ts
packages/server/src/modules/charges/resolvers/common.ts
packages/server/src/modules/charges/typeDefs/charges.graphql.ts
packages/server/src/modules/charges/types.ts
packages/server/src/modules/ledger/helpers/cross-year-ledger.helper.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/common-ledger-generation.resolver.ts

Unequal charge cross-year spreading

---

packages/client/src/components/charges-ledger-validation.tsx

Add default date filters to ledger validation screen

---

packages/client/src/components/layout/dashboard-layout.tsx

Closes #955 
https://github.com/user-attachments/assets/d620552d-fe24-4b1e-97dd-067ca8690674

 Bug: missing scroll on all-charges screen

---

packages/server/src/modules/reports/helpers/profit-and-loss.helper.ts

Refine business trips categorization

---

packages/server/src/modules/ledger/resolvers/ledger-generation/business-trip-ledger-generation.resolver.ts

closes #920
- require documents for amounts > 1000
- if documents exists - use it as default (inastead of business trip transactions)

Better handle documents on business trip charges

---

packages/server/src/modules/ledger/helpers/exchange-ledger.helper.ts
packages/server/src/modules/ledger/helpers/utils.helper.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/bank-deposit-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/business-trip-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/common-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/salary-ledger-generation.resolver.ts

Validate exchange rate + business foreign currencies balance

---

packages/client/src/components/business-trips/editable-business-trip.tsx
packages/client/src/components/business-trips/index.tsx
packages/client/src/components/common/business-trip-report/business-trip-summarized-report.tsx
packages/client/src/components/common/business-trip-report/buttons/accountant-approval.tsx
packages/client/src/components/common/business-trip-report/parts/report-header.tsx
packages/client/src/hooks/use-toggle-business-trip-accountant-approval.ts
packages/migrations/src/actions/2024-08-06T08-47-51.business-trip-accountant-approval.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules/accountant-approval/resolvers/accountant-approval.resolver.ts
packages/server/src/modules/accountant-approval/typeDefs/accountant-approval.graphql.ts
packages/server/src/modules/business-trips/providers/business-trips.provider.ts

Enable accountant approval on business trips

---

packages/client/src/components/common/business-trip-report/buttons/add-other-transaction.tsx
packages/client/src/components/common/business-trip-report/parts/other-row.tsx
packages/client/src/components/common/business-trip-report/parts/other.tsx
packages/migrations/src/actions/2024-08-06T14-00-00.add-description-to-business-trip-other-transaction.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules/business-trips/providers/business-trips-transactions-other.provider.ts
packages/server/src/modules/business-trips/resolvers/business-trips-transactions.resolver.ts
packages/server/src/modules/business-trips/resolvers/business-trips.resolver.ts
packages/server/src/modules/business-trips/typeDefs/business-trip-transactions.graphql.ts
packages/server/src/modules/business-trips/typeDefs/business-trips.graphql.ts

Add description to business trip "other" transaction

---

packages/client/src/components/common/business-trip-report/parts/core-transaction-row.tsx
packages/migrations/src/actions/2024-08-06T15-00-00.enhance-business-trip-transactions-matching.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules/business-trips/helpers/business-trip-report.helper.ts
packages/server/src/modules/business-trips/providers/business-trips-transactions-accommodations.provider.ts
packages/server/src/modules/business-trips/providers/business-trips-transactions-flights.provider.ts
packages/server/src/modules/business-trips/providers/business-trips-transactions-other.provider.ts
packages/server/src/modules/business-trips/providers/business-trips-transactions-travel-and-subsistence.provider.ts
packages/server/src/modules/business-trips/providers/business-trips-transactions.provider.ts
packages/server/src/modules/business-trips/resolvers/business-trip-summary.resolver.ts
packages/server/src/modules/business-trips/resolvers/business-trips-transactions.resolver.ts
packages/server/src/modules/business-trips/resolvers/common.ts
packages/server/src/modules/business-trips/typeDefs/business-trips.graphql.ts
packages/server/src/modules/business-trips/types.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/business-trip-ledger-generation.resolver.ts

many to many link: transactions - business trip expenses

---

.changeset/@accounter_client-1049-dependencies.md
.changeset/few-gifts-unite.md
packages/server/src/modules/ledger/helpers/common-charge-ledger.helper.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/common-ledger-generation.resolver.ts

Better treat refund charges

---

packages/server/src/modules/ledger/resolvers/ledger-generation/bank-deposit-ledger-generation.resolver.ts

Fix: use withdrawal date for both dates in bank deposit exchange rate ledger

---

packages/client/src/components/common/forms/business-card.tsx
packages/client/src/components/common/forms/edit-charge.tsx
packages/client/src/components/common/forms/modify-business-fields.tsx
packages/client/src/components/common/merge-charges/merge-charges-selection-form.tsx
packages/client/src/components/common/modals/edit-charge-modal.tsx
packages/migrations/src/actions/2024-08-12T17-21-10.optional-vat-flag.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules/charges/helpers/validate.helper.ts
packages/server/src/modules/charges/providers/charges.provider.ts
packages/server/src/modules/charges/resolvers/charges.resolver.ts
packages/server/src/modules/charges/typeDefs/charges.graphql.ts
packages/server/src/modules/financial-entities/providers/businesses.provider.ts
packages/server/src/modules/financial-entities/resolvers/businesses.resolver.ts
packages/server/src/modules/financial-entities/typeDefs/businesses.graphql.ts

Optional vat flag for business and charge

---

packages/client/src/components/common/business-trip-report/buttons/add-accommodation-expense.tsx
packages/client/src/components/common/business-trip-report/buttons/add-flight-expense.tsx
packages/client/src/components/common/business-trip-report/parts/accommodations-row.tsx
packages/client/src/components/common/business-trip-report/parts/accommodations.tsx
packages/client/src/components/common/business-trip-report/parts/attendee-stay-input.tsx
packages/client/src/components/common/business-trip-report/parts/core-expense-row.tsx
packages/client/src/components/common/business-trip-report/parts/flights-row.tsx
packages/client/src/components/common/business-trip-report/parts/flights.tsx
packages/client/src/components/common/graphql/attendees-by-business-trip.graphql.ts
packages/migrations/src/actions/2024-08-13T12-57-25.attendees-info-for-trip-accommodation-flights-expenses.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules/business-trips/providers/business-trips-attendees.provider.ts
packages/server/src/modules/business-trips/providers/business-trips-expenses-accommodations.provider.ts
packages/server/src/modules/business-trips/providers/business-trips-expenses-flights.provider.ts
packages/server/src/modules/business-trips/resolvers/business-trips-expenses.resolver.ts
packages/server/src/modules/business-trips/typeDefs/business-trip-expenses.graphql.ts

Employees info for trip accommodation flights expenses

---

.changeset/@accounter_client-1098-dependencies.md
.eslintrc.cjs
codegen.ts
packages/client/package.json
packages/client/src/app.tsx
packages/client/src/components/charts/monthly-income-expense/chart-filter.tsx
packages/client/src/components/charts/monthly-income-expense/chart.tsx
packages/client/src/components/charts/monthly-income-expense/index.tsx
packages/client/src/components/layout/sidelinks.tsx
packages/client/src/providers/index.tsx
packages/server/src/modules-app.ts
packages/server/src/modules/charts/index.ts
packages/server/src/modules/charts/resolvers/charts.resolver.ts
packages/server/src/modules/charts/typeDefs/charts.graphql.ts
packages/server/src/modules/charts/types.ts
yarn.lock

Monthly income outcome chart

---

packages/client/src/components/business-transactions/business-transactions-single.tsx
packages/client/src/components/business-transactions/index.tsx
packages/client/src/components/reports/trial-balance-report/index.tsx
packages/client/src/components/reports/trial-balance-report/trial-balance-report-account.tsx
packages/client/src/components/reports/trial-balance-report/trial-balance-table.tsx
packages/server/src/modules/financial-entities/resolvers/business-transactions.resolver.ts
packages/server/src/modules/financial-entities/typeDefs/businesses-transactions.graphql.ts

Enable all-currencies view on business transactions screen

---

packages/client/src/components/business-transactions/business-extended-info.tsx
packages/server/src/modules/financial-entities/resolvers/business-transactions.resolver.ts
packages/server/src/modules/financial-entities/typeDefs/businesses-transactions.graphql.ts

Enable all-currencies view on business transactions screen2

---

packages/server/src/modules/ledger/helpers/cross-year-ledger.helper.ts

Enhance charge year spread - adjust for multiple documents charges

---

codegen.ts
packages/client/src/components/all-charges/charge-extended-info.tsx
packages/client/src/components/common/deprecation/add-deprecation-record.tsx
packages/client/src/components/common/deprecation/delete-deprecation-record.tsx
packages/client/src/components/common/deprecation/deprecation-row.tsx
packages/client/src/components/common/deprecation/index.tsx
packages/client/src/components/common/forms/edit-charge.tsx
packages/client/src/components/common/graphql/all-deprecation-categories.graphql.ts
packages/client/src/components/reports/tax-report/index.tsx
packages/client/src/hooks/use-add-deprecation-record.ts
packages/client/src/hooks/use-delete-deprecation-record.ts
packages/client/src/hooks/use-update-deprecation-record.ts
packages/migrations/src/actions/2024-08-28T16-07-43.deprecation.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules-app.ts
packages/server/src/modules/charges/helpers/common.helper.ts
packages/server/src/modules/charges/resolvers/common.ts
packages/server/src/modules/deprecation/index.ts
packages/server/src/modules/deprecation/providers/deprecation-categories.provider.ts
packages/server/src/modules/deprecation/providers/deprecation.provider.ts
packages/server/src/modules/deprecation/resolvers/deprecation.resolver.ts
packages/server/src/modules/deprecation/typeDefs/deprecation.graphql.ts
packages/server/src/modules/deprecation/types.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/financial-ledger-generation/tax-expenses-ledger-generation.resolver.ts
packages/server/src/modules/reports/helpers/tax.helper.ts
packages/server/src/modules/reports/helpers/vat-report.helper.ts
packages/server/src/modules/reports/resolvers/reports/tax-report.ts
packages/server/src/modules/reports/typeDefs/tax-report.graphql.ts

Implement deprecation module

---

.changeset/@accounter_server-1128-dependencies.md
.changeset/@accounter_server-1155-dependencies.md
packages/server/package.json
yarn.lock

Reverts Urigo/accounter-fullstack#1128

Revert "fix(deps): update dependency @envelop/generic-auth to v8"

---

codegen.ts
packages/migrations/src/actions/2024-09-04T15-37-43.company-taxes.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules-app.ts
packages/server/src/modules/corporate-taxes/index.ts
packages/server/src/modules/corporate-taxes/providers/corporate-taxes.provider.ts
packages/server/src/modules/corporate-taxes/resolvers/corporate-taxes.resolver.ts
packages/server/src/modules/corporate-taxes/typeDefs/corporate-taxes.graphql.ts
packages/server/src/modules/corporate-taxes/types.ts
packages/server/src/modules/reports/helpers/tax.helper.ts

Introduce corporate taxes module

---

packages/client/src/components/common/business-trip-report/parts/summary.tsx
packages/server/src/modules/business-trips/helpers/business-trip-report.helper.ts
packages/server/src/modules/business-trips/typeDefs/business-trips.graphql.ts
packages/server/src/modules/exchange-rates/providers/crypto-exchange.provider.ts
packages/server/src/modules/exchange-rates/providers/fiat-exchange.provider.ts

Business trip summary include max taxable amounts

---

packages/server/src/modules/ledger/helpers/common-charge-ledger.helper.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/business-trip-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/common-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/internal-transfer-ledger-generation.resolver.ts
packages/server/src/modules/transactions/helpers/effective-date.helper.ts

Exchange rates ledger: use latest transaction value date

---

packages/server/src/modules/ledger/resolvers/ledger-generation/financial-ledger-generation.resolver.ts
packages/server/src/modules/ledger/resolvers/ledger-generation/financial-ledger-generation/revaluation-ledger-generation.resolver.ts

Fix: exchange revaluation charge ledger generation

---

packages/client/src/components/common/business-trip-report/parts/report-header.tsx

Fix: trip reports days miscalculation

---

packages/server/src/modules/business-trips/helpers/business-trip-report.helper.ts

Fix business trips excess expenditure calculation

---

packages/migrations/src/actions/2024-12-16T09-31-25.amex-scraper-completion.ts
packages/migrations/src/run-pg-migrations.ts

Amex migration missing parts completion

---

packages/server/src/modules/business-trips/helpers/business-trip-report.helper.ts
packages/server/src/modules/business-trips/providers/business-trips-attendees.provider.ts
packages/server/src/modules/business-trips/resolvers/business-trip-summary.resolver.ts
packages/server/src/modules/business-trips/types.ts

Enhance business trip reports: handle consecutive trips accommodation

---

packages/migrations/src/actions/2025-01-05T18-20-42.vat-table.ts
packages/migrations/src/run-pg-migrations.ts
packages/server/src/modules-app.ts
packages/server/src/modules/documents/helpers/validate-document-vat.helper.ts
packages/server/src/modules/ledger/helpers/common-charge-ledger.helper.ts
packages/server/src/modules/reports/helpers/vat-report.helper.ts
packages/server/src/modules/vat/index.ts
packages/server/src/modules/vat/providers/vat.provider.ts
packages/server/src/modules/vat/typeDefs/vat.graphql.ts
packages/server/src/modules/vat/types.ts
packages/server/src/shared/constants.ts

Feature: adjustable VAT value

---

packages/client/src/components/business-transactions/business-extended-info.tsx
packages/client/src/components/business-transactions/download-csv.tsx

Feature: export business transactions date to CSV

---

packages/client/src/components/business-transactions/business-extended-info.tsx
packages/client/src/components/business-transactions/business-transactions-single.tsx
packages/client/src/components/business-transactions/index.tsx
packages/client/src/components/charts/index.tsx
packages/client/src/helpers/currency.ts
packages/migrations/src/actions/2025-01-12T11-47-46.support-cad-currency.ts
packages/migrations/src/run-pg-migrations.ts
packages/scraper-local-app/src/scrapers/currency-rates.ts
packages/server/src/modules/common/typeDefs/common.graphql.ts
packages/server/src/modules/exchange-rates/helpers/exchange.helper.ts
packages/server/src/modules/exchange-rates/resolvers/exchange.resolver.ts
packages/server/src/modules/exchange-rates/typeDefs/exchange.graphql.ts
packages/server/src/shared/enums.ts
packages/server/src/shared/helpers/amount.ts

Support CAD currency

---

packages/client/src/components/reports/profit-and-loss-report/index.tsx
packages/server/src/modules/ledger/resolvers/ledger-generation/financial-ledger-generation/tax-expenses-ledger-generation.resolver.ts
packages/server/src/modules/reports/helpers/tax.helper.ts
packages/server/src/modules/reports/resolvers/reports/tax-report.ts

Yearly tax report fixes

---

packages/client/src/components/reports/corporate-tax-ruling-compliance-report/amount-cell.tsx
packages/client/src/components/reports/corporate-tax-ruling-compliance-report/index.tsx

Enhance corporate ruling report: add summary column

---

.changeset/@accounter_server-1737-dependencies.md
package.json
packages/scraper-local-app/package.json
packages/server/package.json
yarn.lock

Reverts Urigo/accounter-fullstack#1737

Revert "fix(deps): update dependency @pgtyped/cli to v2.4.2"

---

packages/server/src/modules/reports/helpers/pcn.helper.ts

Fix: use local VAT amounts on PCN

---

packages/migrations/src/actions/2025-07-30T19-01-04.jpy-rate-fix.ts
packages/migrations/src/run-pg-migrations.ts
packages/scraper-local-app/src/scrapers/currency-rates.ts

Fix: JPY exchange rate

---

.changeset/good-eels-look.md
packages/client/src/components/charges/charge-extended-info.tsx
packages/client/src/components/common/documents/issue-document/index.tsx
packages/client/src/components/common/documents/issue-document/issue-document-modal.tsx
packages/client/src/components/common/modals/issue-document-modal.tsx
packages/client/src/components/documents-table/columns.tsx
packages/server/src/modules/green-invoice/helpers/green-invoice.helper.ts
packages/server/src/modules/green-invoice/helpers/issue-document.helper.ts
packages/server/src/modules/green-invoice/resolvers/green-invoice.resolvers.ts
packages/server/src/modules/green-invoice/typeDefs/green-invoice.graphql.ts

Issue documents related enhancements

---

packages/client/src/components/common/documents/issue-document/index.tsx
packages/client/src/components/common/modals/preview-document-modal.tsx
packages/client/src/hooks/use-issue-document.ts
packages/server/src/modules/green-invoice/resolvers/green-invoice.resolvers.ts

Fix: transaction-based document issue

---

packages/server/src/modules/green-invoice/resolvers/green-invoice.resolvers.ts

Fix: close invoice on receipt issue

---

.changeset/brave-chairs-wait.md
packages/server/src/modules/app-providers/green-invoice-client.ts
packages/server/src/modules/documents/resolvers/documents.resolver.ts
packages/server/src/modules/financial-entities/resolvers/clients.resolvers.ts
packages/server/src/modules/green-invoice/helpers/green-invoice.helper.ts
packages/server/src/modules/green-invoice/helpers/issue-document.helper.ts
packages/server/src/modules/green-invoice/resolvers/green-invoice.resolvers.ts

Add dataloaders and caching to Green Invoice, fix document status update
